# -*- coding: utf-8 -*-
"""task.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18ykVc-NOtb99DUIKw_uhnVB2PZLwg0gi
"""

import numpy as np
m=int(input("enter row size"))
n=int(input("enter column size"))
x=np.empty((m,n))
for k in range(m+n-1):
  for i in range(m):
    for j in range(n):
      if(i+j==k):
        x[i][j]=int(input())
print(x)